name: "gdsciitnmbackend"

services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gdsc_iitnm
    ports:
      - "5500:5432"
